export const COLORS = {
    SURFACE_WHITE: "#FFFFFF",
    SURFACE_LIGHT: "#F7F7F7",
    BACKGROUND: "#EDEDED",
    MID_GRAY: "#BDBDBD",
    DARK_GRAY: "#666666",
    TEXT: "#333333",
    SOFT_YELLOW: "#FFFDE7",
    PRIMARY_YELLOW: "#F0F036",
    DARK_YELLOW: "#C8C800"
}