name: dummies_investments
services:
  front:
    build:
      context: ./front/fin-profi
      dockerfile: ../Dockerfile
      target: development
    volumes:
      - ./front/fin-profi:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - FAST_REFRESH=true
    ports:
      - "3000:5173"
    networks:
      - app
    depends_on:
      - back
    command: npm run dev -- --host

  back:
    build: ./back
    ports:                  
      - "8000:80"               
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file: "db.env"
    environment:
      POSTGRES_DB: dummies_investments
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app

volumes:
  pgdata:
    driver: local

networks:
  app:
    name: app